new message category blocks
ComputeCycles/scratch-gui pull request #10
Opened 2021-05-14 21:54 UTC by bschweiz

### Resolves

_What Github issue does this resolve (please include link)?_

- Resolves #

### Proposed Changes

adds new message category blocks for communicating with MQTT servers

_Describe what this Pull Request does_

### Reason for Changes

_Explain why these changes should be made_

### Test Coverage

_Please show how you have added tests to cover your changes_

### Browser Coverage
Check the OS/browser combinations tested (At least 2)

Mac
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Safari
 
Windows
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Edge
 
Chromebook
 * [ ] Chrome
 
iPad
* [ ] Safari

Android Tablet
* [ ] Chrome

2021-05-15 21:42 UTC, rvsrvs requested changes

2021-05-15 21:42 UTC, rvsrvs commented on src/lib/make-toolbox-xml.js
> +            case '<': return '&lt;';
tabs an inconsistent indentation.  you may want to make sure you are using the linter format as specified in the directory.

2021-05-17 14:32 UTC, bschweiz commented on src/lib/make-toolbox-xml.js
> +            case '<': return '&lt;';
addressed

2021-05-17 14:34 UTC, bschweiz reviewed
indentation issues fixed

2021-05-17 17:03 UTC, merged